name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '17', '21']
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ contains(matrix.os, 'windows') }}
      - name: Build
        run: ./gradlew :server:build :shared:build -PjavaVersion=${{ matrix.java }}
      - name: Detekt
        run: ./gradlew detekt -PjavaVersion=${{ matrix.java }}
